build-debian-pc-debug-gcc:
  image: gcc
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install tzdata
    - apt -y install make pkg-config libusb-1.0-0-dev git
    - git submodule update --init
  script:
    - cd tools/pc_debug && make

build-esp-idf-4.4:
  image: espressif/idf:release-v4.4
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install tzdata
    - apt -y install git
    - git submodule update --init
    - pushd .
    - cd external/btstack/port/esp32
    - IDF_PATH=../../../../src/ ./integrate_btstack.py
    - popd
  script:
    - pushd .
    - cd src
    # For more complex examples, see:
    # https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/multi_config/README.md
    - idf.py -B build_plat_uni -D SDKCONFIG_DEFAULTS="sdkconfig.ci.plat_unijoysticle" build
    - popd
