build-debian-pc-debug-gcc:
  image: gcc
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install tzdata
    - apt -y install make pkg-config libusb-1.0-0-dev git
    - git submodule update --init
  script:
    - cd tools/pc_debug && make

build-esp-idf-4.4:
  image: espressif/idf:release-v4.4
  script:
    - cd src
    - idf.py build
