site_name: Bluepad32
site_url: https://retro.moe/
site_author: Ricardo Quesada
copyright: Copyright &copy; 2019-2024 Ricardo Quesada & contributors

repo_url: https://github.com/ricardoquesada/bluepad32
repo_name: ricardoquesada/bluepad32
edit_uri: blob/develop/docs

watch:
  - README.md
  - CHANGELOG.md
  - AUTHORS.md
  - LICENSE

nav:
  - Home: index.md
  - Getting Started:
    - getting_started.md
    - getting_help.md
  - Controllers:
    - supported_gamepads.md
    - supported_mice.md
    - supported_keyboards.md
    - pair_ds3.md
  - Platforms:
    - 'Arduino + ESP32 boards': plat_arduino.md
    - 'Arduino + NINA boards': plat_nina.md
    - 'CircuitPython + AirLift boards': plat_airlift.md
    - 'Unijoysticle board': plat_unijoysticle.md
    - 'MightyMiggy board': plat_mightymiggy.md
  - Developer:
    - 'Flashing firmware': firmware_setup.md
    - adding_new_platform.md
    - 'Architecture': architecture.md
    - developer_notes.md
    - 'Release Notes': release_notes.md
    - 'Issue Tracker': https://github.com/ricardoquesada/bluepad32/issues
  - About:
    - Authors: authors.md
    - license.md

theme:
  name: material
  features:
    - navigation.expand
  font: false
  icon:
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: G-FXKBEY2NKF

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - include-markdown
